# Generated by Django 6.0.6 on 2026-06-26 07:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20)),
                ('avatar', models.URLField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subject_name', models.CharField(max_length=255)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('semester', models.IntegerField()),
                ('exam_date', models.CharField(max_length=50)),
                ('exam_time', models.CharField(max_length=50)),
                ('duration', models.CharField(default='3 hours', max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'exams',
                'indexes': [models.Index(fields=['subject_code'], name='exams_subject_9d6c8a_idx'), models.Index(fields=['department'], name='exams_departm_022a01_idx'), models.Index(fields=['is_deleted'], name='exams_is_dele_25d336_idx'), models.Index(fields=['department', 'semester'], name='idx_exam_dept_sem')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All'), ('students', 'Students'), ('teachers', 'Teachers'), ('admin', 'Admin')], db_index=True, max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['audience'], name='notificatio_audienc_9ca9e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('semester', models.IntegerField(default=1)),
                ('section', models.CharField(default='A', max_length=10)),
                ('photo', models.URLField(blank=True, max_length=512, null=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('internal_marks', models.FloatField(default=0.0)),
                ('assignment_marks', models.FloatField(default=0.0)),
                ('previous_result', models.FloatField(default=0.0)),
                ('backlogs', models.IntegerField(default=0)),
                ('fee_paid', models.BooleanField(db_index=True, default=False)),
                ('fee_amount', models.FloatField(default=45000.0)),
                ('fee_due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('is_eligible', models.BooleanField(db_index=True, default=False)),
                ('eligibility_percentage', models.FloatField(default=0.0)),
                ('ai_risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=50)),
                ('internal_score', models.FloatField(default=0.0)),
                ('assignment_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_records', to='api.student')),
            ],
            options={
                'db_table': 'internal_marks',
            },
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_ticket_no', models.CharField(db_index=True, max_length=100, unique=True)),
                ('seat_number', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=100)),
                ('qr_code_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='api.exam')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall_ticket', to='api.student')),
            ],
            options={
                'db_table': 'hall_tickets',
            },
        ),
        migrations.CreateModel(
            name='EligibilityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_probability', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('factors_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.student')),
            ],
            options={
                'db_table': 'eligibility_predictions',
            },
        ),
        migrations.CreateModel(
            name='ChatbotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('bot_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_logs', to='api.student')),
            ],
            options={
                'db_table': 'chatbot_logs',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(db_index=True, max_length=50)),
                ('record_date', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.student')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('photo', models.URLField(blank=True, max_length=512, null=True)),
                ('assigned_subjects', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted'], name='users_is_dele_21b557_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_no'], name='students_roll_no_eef286_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='students_departm_33c447_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_deleted'], name='students_is_dele_51b572_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['fee_paid'], name='students_fee_pai_7c2459_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_eligible'], name='students_is_elig_c31e72_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'semester'], name='idx_student_dept_sem'),
        ),
        migrations.AddIndex(
            model_name='internalmark',
            index=models.Index(fields=['student'], name='internal_ma_student_3ab680_idx'),
        ),
        migrations.AddIndex(
            model_name='internalmark',
            index=models.Index(fields=['subject_code'], name='internal_ma_subject_a00929_idx'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['hall_ticket_no'], name='hall_ticket_hall_ti_d6a7e1_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilityprediction',
            index=models.Index(fields=['student'], name='eligibility_student_8d8b39_idx'),
        ),
        migrations.AddIndex(
            model_name='chatbotlog',
            index=models.Index(fields=['student'], name='chatbot_log_student_9598db_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student'], name='attendance_student_5b1d70_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['subject_code'], name='attendance_subject_2696f1_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['record_date'], name='attendance_record__514447_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['emp_id'], name='teachers_emp_id_3a740e_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teachers_departm_174d34_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['is_deleted'], name='teachers_is_dele_3d3085_idx'),
        ),
    ]
