# Generated by Django 4.2.30 on 2026-07-03 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('room_name', models.CharField(max_length=255)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('floor', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=60)),
                ('rows', models.IntegerField(default=10)),
                ('columns', models.IntegerField(default=6)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'seating_rooms',
                'indexes': [models.Index(fields=['room_code'], name='seating_roo_room_co_295803_idx'), models.Index(fields=['is_active'], name='seating_roo_is_acti_e922f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeatingArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_row', models.IntegerField()),
                ('seat_column', models.IntegerField()),
                ('seat_number', models.CharField(max_length=20)),
                ('arrangement_type', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_arrangements', to='api.exam')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_arrangements', to='api.seatingroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_assignments', to='api.student')),
            ],
            options={
                'db_table': 'seating_arrangements',
                'indexes': [models.Index(fields=['exam'], name='seating_arr_exam_id_e7e9d9_idx'), models.Index(fields=['room'], name='seating_arr_room_id_f6f1fa_idx'), models.Index(fields=['student'], name='seating_arr_student_ada944_idx'), models.Index(fields=['exam', 'room'], name='seating_arr_exam_id_2f1d8b_idx')],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
