# Generated by Django 4.2.30 on 2026-07-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seatingroom_seatingarrangement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeatingArrangement',
        ),
        migrations.DeleteModel(
            name='SeatingRoom',
        ),
    ]
