# Generated by Django 4.2.30 on 2026-07-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_exam_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('photo', models.URLField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'db_table': 'hods',
            },
        ),
        migrations.RenameIndex(
            model_name='department',
            new_name='departments_is_acti_a777bd_idx',
            old_name='departments_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='examsubject',
            new_name='exam_subjec_exam_id_a4594b_idx',
            old_name='idx_exam_subject_exam',
        ),
        migrations.RenameIndex(
            model_name='examsubject',
            new_name='exam_subjec_subject_00d695_idx',
            old_name='idx_exam_subject_code',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='fee_payment_student_17503f_idx',
            old_name='fee_payment_student_idx',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='fee_payment_transac_ead7fa_idx',
            old_name='fee_payment_txn_idx',
        ),
        migrations.RenameIndex(
            model_name='feepayment',
            new_name='fee_payment_status_d14ebc_idx',
            old_name='fee_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='hallticketsubject',
            new_name='hall_ticket_hall_ti_b35ba9_idx',
            old_name='idx_ht_subject_ticket',
        ),
        migrations.RenameIndex(
            model_name='hallticketsubject',
            new_name='hall_ticket_subject_28a006_idx',
            old_name='idx_ht_subject_code',
        ),
        migrations.RenameIndex(
            model_name='hallticketsubject',
            new_name='hall_ticket_exam_id_1aaa6c_idx',
            old_name='idx_ht_subject_exam_code',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'Hod'), ('teacher', 'Teacher'), ('student', 'Student')], max_length=20),
        ),
        migrations.AddField(
            model_name='hod',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='hod',
            index=models.Index(fields=['emp_id'], name='hods_emp_id_7c7186_idx'),
        ),
        migrations.AddIndex(
            model_name='hod',
            index=models.Index(fields=['department'], name='hods_departm_420419_idx'),
        ),
        migrations.AddIndex(
            model_name='hod',
            index=models.Index(fields=['is_deleted'], name='hods_is_dele_60adef_idx'),
        ),
    ]
